<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, image slider jquery, javascript slideshow" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="{{Asset('public/assets/engine1/style.css')}}" />
	<script type="text/javascript" src="{{Asset('public/assets/engine1/jquery.js')}}"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="{{Asset('public/assets/data1/images/anh11.jpg')}}" alt="anh-1-1" title="anh-1-1" id="wows1_0"/></li>
<li><img src="{{Asset('public/assets/data1/images/slide1.jpg')}}" alt="slide-1" title="slide-1" id="wows1_1"/></li>
</ul></div>
<span class="wsl"><a href="http://wowslider.net">wordpress slider</a> by WOWSlider.com v5.5</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="{{Asset('public/assets/engine1/wowslider.js')}}"></script>
	<script type="text/javascript" src="{{Asset('public/assets/engine1/script.js')}}"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>