<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, image slider, responsive slider" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="{{asset('public/assets/engine1/style.css')}}" />
	<script type="text/javascript" src="{{asset('public/assets/engine1/jquery.js')}}"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#eeeeee">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="{{asset('public/assets/data1/images/cafecachewaiter.jpg')}}" alt="Cafe-Cache-waiter" title="Cafe-Cache-waiter" id="wows1_0"/></li>
<li><img src="{{asset('public/assets/data1/images/saltwatercafechurchgate2.jpg')}}" alt="Salt-Water-Cafe-Churchgate-2" title="Salt-Water-Cafe-Churchgate-2" id="wows1_1"/></li>
<li><img src="{{asset('public/assets/data1/images/ordinaryfantasticgrungyvintageindustrialcafeinterioridea.jpg')}}" alt="ordinary-fantastic-grungy-vintage-industrial-cafe-interior-idea" title="ordinary-fantastic-grungy-vintage-industrial-cafe-interior-idea" id="wows1_2"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="Cafe-Cache-waiter"><img src="{{asset('public/assets/data1/tooltips/cafecachewaiter.jpg')}}" alt="Cafe-Cache-waiter"/>1</a>
<a href="#" title="Salt-Water-Cafe-Churchgate-2"><img src="{{asset('public/assets/data1/tooltips/saltwatercafechurchgate2.jpg')}}" alt="Salt-Water-Cafe-Churchgate-2"/>2</a>
<a href="#" title="ordinary-fantastic-grungy-vintage-industrial-cafe-interior-idea"><img src="{{asset('public/assets/data1/tooltips/ordinaryfantasticgrungyvintageindustrialcafeinterioridea.jpg')}}" alt="ordinary-fantastic-grungy-vintage-industrial-cafe-interior-idea"/>3</a>
</div></div>
<span class="wsl"><a href="http://wowslider.net">slideshow jquery</a> by WOWSlider.com v5.5</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="{{asset('public/assets/engine1/wowslider.js')}}"></script>
	<script type="text/javascript" src="{{asset('public/assets/engine1/script.js')}}"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>